# Generated by Django 5.1.7 on 2025-04-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmng', '0002_alter_task_reporter'),
    ]

    operations = [
        migrations.AddField(
            model_name='priority',
            name='description',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
