# Generated by Django 5.1.7 on 2025-04-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmng', '0002_remove_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='taskmng/media/avatar-svgrepo-com.svg', null=True, upload_to=''),
        ),
    ]
