# Generated by Django 5.1.7 on 2025-04-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmng', '0003_priority_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priority',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
