# Generated by Django 5.1.7 on 2025-04-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmng', '0004_alter_priority_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priority',
            name='description',
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
