# Generated by Django 5.1.7 on 2025-04-27 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmng', '0004_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default=None, null=True, upload_to='avatars/'),
        ),
    ]
