# Generated by Django 5.1.7 on 2025-05-21 20:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmng', '0007_rename_task_messages_task_task_assignee_invitation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='member',
            field=models.ManyToManyField(blank=True, related_name='projects', through='taskmng.ProjectMember', to=settings.AUTH_USER_MODEL),
        ),
    ]
